# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  ovms-service:
    image: openvino/model_server:2025.3-gpu
    devices:
      - ${DRI_MOUNT_PATH:-/dev/null}:/dev/dri
    group_add:
      - ${RENDER_DEVICE_GID:-0}
