global:
  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  env:
    APP_ENDPOINT_URL: "/manager"
    APP_ASSETS_URL: "/minio"

name: videosummaryui
image:
  repository: intel/vss-ui
  tag: "1.2.3"
  pullPolicy: IfNotPresent

containerPortName: vs-ui-port  # Optional name to refer containerPort
service:
  type: ClusterIP
  port: 80  # Port on which service listens for incoming connection

feature:
  summary: "FEATURE_OFF"
  search: "FEATURE_ON"
  mux: "ATOMIC"