apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modeldownload.name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.modeldownload.service.type }}
  ports:
    - nodePort: {{ .Values.modeldownload.service.nodePort }}
      port: {{ .Values.modeldownload.service.port }}
      targetPort: 8000
  selector:
    app: {{ .Chart.Name }}