apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-config
data:
  nginx.conf: |
    pid /tmp/nginx.pid;

    events{}

    http {
      server {
        listen 8102;
        listen [::]:8102;

        client_max_body_size 500M;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;

        location / {
              proxy_pass http://{{ index .Values "uiService" "name" }}:{{ index .Values "uiService" "port" }};
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_cache_bypass $http_upgrade;
        }
        location /v1/chatqna {
              proxy_pass http://{{ index .Values "chatqna" "name" }}:{{ index .Values "chatqna" "service" "port" }};
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_cache_bypass $http_upgrade;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nginx.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx.fullname" . }}
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.29.2
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8102
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  selector:
    app: {{ include "nginx.fullname" . }}
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
      nodePort: {{ .Values.global.ui_nodeport }}
  type: NodePort
