# Common PVC that can be shared across sub-charts
{{- if and (.Values.global.usePvc) (.Values.vdmsdataprep.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.sharedPvcName | default "vss-pvc" }}
  {{- if .Values.global.keepPvc }}
  annotations:
    helm.sh/resource-policy: keep   # Prevent Helm from deleting PVC on uninstall
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharedClaimSize | default "10Gi" }}
{{- end }}
