{{- if .Values.global.usePvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- if .Values.global.gpu.vlminferenceEnabled }}
  name: {{ include "vlminference.fullname" . }}-gpu-pvc
{{- else }}
  name: {{ include "vlminference.fullname" . }}-pvc
{{- end }}
  {{- if .Values.global.keepPvc }}
  annotations:
    helm.sh/resource-policy: keep   # Prevent Helm from deleting PVC on uninstall
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.claimSize | default "10Gi" }}
{{- end }}
