{{- if .Values.global.usePvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vlminference.fullname" . }}-pvc
  {{- if .Values.global.keepPvc }}
  annotations:
    helm.sh/resource-policy: keep   # Prevent Helm from deleting PVC on uninstall
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.claimSize | default "10Gi" }}
{{- end }}
