# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
services:
  dataprep_microservice:
    build:
      target: dev
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    #TODO: Configure image version as an env parameter 
    image: intel/document-ingestion:1.2.2-dev
    environment:
      DEFAULT_BUCKET: "intel.gai.dev.test"
      OBJECT_PREFIX: "test"
    volumes:
      - "../app:/app/app"
    restart: always
