apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "multimodal-embedding-ms.fullname" . }}
  labels:
    {{- include "multimodal-embedding-ms.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "multimodal-embedding-ms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "multimodal-embedding-ms.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podAffinity }}
      affinity:
        podAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ ternary .Values.image.gpu.repository .Values.image.cpu.repository .Values.global.gpu.multimodalembeddingmsEnabled }}:{{ ternary .Values.image.tag .Values.global.commonTag (empty .Values.global.commonTag) | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
          ports:
            - name: {{ .Values.containerPortName }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "multimodal-embedding-ms.fullname" . }}-config
      {{- if .Values.global.gpu.multimodalembeddingmsEnabled }}
          resources:
            requests:
              {{ .Values.global.gpu.key}}: 1
            limits:
              {{ .Values.global.gpu.key}}: 1
      {{- else }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: volume-data
              mountPath: /home/appuser/.cache/huggingface
              subPath: huggingface
            - name: volume-data
              mountPath: /app/ov_models
              subPath: ovmodels
            - name: volume-data
              mountPath: /tmp/dataprep
              subPath: tmpvideos
      {{- if .Values.global.gpu.multimodalembeddingmsEnabled }}
            - name: workspace
              mountPath: /opt/data
              subPath: ovmodels
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
      {{- if .Values.global.gpu.multimodalembeddingmsEnabled }}
        - name: dri-device
          hostPath:
            path: /dev/dri
            type: Directory
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ include "multimodal-embedding-ms.fullname" . }}-gpu-pvc
      {{- end }}
        - name: volume-data
          {{- if .Values.global.usePvc }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.sharedPvcName | default "vss-pvc" }}
          {{- else if .Values.global.volumeHostPath }}
          hostPath:
            path: {{ .Values.global.volumeHostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
