global:
  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  keeppvc: false

replicaCount: 1

modeldownload:
  name: model-download
  image:
    registry: "intel/"
    tag: 1.0.1
    pullPolicy: IfNotPresent

  readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
    
  env:
    HUGGINGFACEHUB_API_TOKEN: ""
    ENABLED_PLUGINS: "all"   #Comma separated list of plugins to enable, or "all"

  service:
    type: NodePort
    nodePort: 
    port: 8000
