# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "chatqna"
displayName: "chatqna"
description: "Chat Q&A Sample Application"
version: "2.0.0"

applications:
  - name: chatqna-app
    version: 2.0.0

defaultNamespaces:
  chatqna-app: chatqna

deploymentProfiles:
  - name: "ovms"
    applicationProfiles:
      - application: "chatqna-app"
        profile: "ovms"