Kp_config:
  kp: 40
  kp_large: 500
Kd_config:
  kd: 1
LeggedRobotCfg:
  init_state:
    default_joint_angle:
      leg_l1_joint: -0.0
      leg_l2_joint: 0.03
      leg_l3_joint: -0.025
      leg_l4_joint: 0.05
      leg_l5_joint: -0.025
      leg_l6_joint: -0.0
      leg_r1_joint: -0.0
      leg_r2_joint: -0.03
      leg_r3_joint: -0.025
      leg_r4_joint: 0.05
      leg_r5_joint: -0.025
      leg_r6_joint: -0.0
      l_arm_joint1: 0.0
      l_arm_joint2: 0.0
      r_arm_joint1: 0.0
      r_arm_joint2: 0.0
  control:
    stiffness:
      leg_l1_joint: 50.0
      leg_r1_joint: 50.0
      leg_l2_joint: 60.0
      leg_r2_joint: 60.0
      leg_l3_joint: 90.0
      leg_r3_joint: 90.0
      leg_l4_joint: 120.0
      leg_r4_joint: 120.0
      leg_l5_joint: 50.0
      leg_r5_joint: 50.0
      leg_l6_joint: 30.0
      leg_r6_joint: 30.0
      l_arm_joint1: 70.0
      l_arm_joint2: 70.0
      r_arm_joint1: 70.0
      r_arm_joint2: 70.0
    damping:
      leg_l1_joint: 5.0
      leg_r1_joint: 5.0
      leg_l2_joint: 6.0
      leg_r2_joint: 6.0
      leg_l3_joint: 9.0
      leg_r3_joint: 9.0
      leg_l4_joint: 12.0
      leg_r4_joint: 12.0
      leg_l5_joint: 5.0
      leg_r5_joint: 5.0
      leg_l6_joint: 3.0
      leg_r6_joint: 3.0
      l_arm_joint1: 3.0
      l_arm_joint2: 3.0
      r_arm_joint1: 3.0
      r_arm_joint2: 3.0
    action_scale: 0.5
    decimation: 1
    cycle_time: 1.0
  normalization:
    clip_scales:
      clip_observations: 100.0
      clip_actions: 100.0
    obs_scales:
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 0.05
      height_measurements: 5.0
      lin_vel: 2.0
      quat: 1.0
  size:
    actions_size: 12
    observations_size: 47
    observations_type: 0
    num_hist: 66
  mode:
    sw_mode: true
    cmd_threshold: 0.05
    ang_vel_threshold: 100000
    angle_threshold: 0.1
  filter:
    filt_action: true
    sample_rate: 100
    cutoff_freq: 3.0
  lie_mode:
    kp: 30
    kd: 1
    ankle_kp: 30
    ankle_kd: 0.01
  stand_mode:
    kp: 80
    kd: 1
    ankle_kp: 30
    ankle_kd: 0.1
joint_offsets:
  joint_1: 0.0
  joint_2: 0.005
  joint_3: 0.01
  joint_4: 0.0
  joint_5: 0.0
  joint_6: 0.0
  
  joint_7: 0.0
  joint_8: 0.005
  joint_9: 0.0
  joint_10: -0.0
  joint_11: 0.0
  joint_12: 0.02

  joint_13: 0.0
  joint_14: 0.0
  joint_15: 0.0
  joint_16: 0.0
