model_settings:
  MODEL_RUNTIME: "openvino"
  EMBEDDING_MODEL_ID: "BAAI/bge-small-en-v1.5"
  RERANKER_MODEL_ID: "BAAI/bge-reranker-base"
  LLM_MODEL_ID: "Intel/neural-chat-7b-v3-3"
  PROMPT_TEMPLATE: >
    ### System:
    Use the following pieces of context from retrieved
    dataset to answer the question. Do not make up an answer if there is no
    context provided to help answer it.

    ### Context:
    {context}

    ### User:
    {question}

    ### Assistant:
device_settings:
  EMBEDDING_DEVICE: "CPU"
  RERANKER_DEVICE: "CPU"
  LLM_DEVICE: "CPU"
