model_settings:
  MODEL_RUNTIME: "openvino"
  EMBEDDING_MODEL_ID: "BAAI/bge-small-en-v1.5"
  RERANKER_MODEL_ID: "BAAI/bge-reranker-base"
  LLM_MODEL_ID: "Qwen/Qwen2.5-7B-Instruct"
  PROMPT_TEMPLATE: >
    <|im_start|>
    system:
    Use the following pieces of context from retrieved
    dataset to answer the question. Do not make up an answer if there is no
    context provided to help answer it.

    context:
    {context}
    <|im_end|>

    <|im_start|>
    user:
    {question}
    <|im_end|>

    <|im_start|>
    assistant:
device_settings:
  EMBEDDING_DEVICE: "CPU"
  RERANKER_DEVICE: "CPU"
  LLM_DEVICE: "CPU"
