---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[GEN-AI] Chat-qna-core-CI"
run-name: "[GEN-AI-Chat-qna-core-CI] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"


# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches:
      - ciscans-makefile
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'

env:
  APP_PATH: sample-applications/chat-question-and-answer-core
  APP_NAME: chatqna-core

jobs:
  
  # Job 1: A fast job to generate the dynamic matrix from the Makefile
  setup:
    runs-on: ubuntu-22.04-32core-128GB
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709

      - name: Generate scan matrix from Makefile
        id: set-matrix
        working-directory: ${{ env.APP_PATH }}
        run: echo "matrix=$(make get-scan-matrix-json)" >> $GITHUB_OUTPUT

      - name: Get tool versions from Makefile
        id: set-versions
        working-directory: ${{ env.APP_PATH }}
        run: |
          echo "python=$(make get-python-version)" >> $GITHUB_OUTPUT
          echo "node=$(make get-node-version)" >> $GITHUB_OUTPUT

  # Job 2: Build AND Scan each component in parallel
  build_and_scan:
    runs-on: ubuntu-22.04-32core-128GB
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Run Trivy Filesystem Scan
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        id: trivy-fs
        with:
          scan_type: "fs"  
          scan-scope: "all"  
          severity: "HIGH,CRITICAL" 
          format: "json"
          scan_target: ${{ env.APP_PATH }}
          report_suffix: "-fs-chat-qna-core-CT7"

      - name: Build Docker image for ${{ matrix.name }}
        working-directory: ${{ env.APP_PATH }}
        run: make build-${{ matrix.name }}

      - name: Run Trivy Image Scan - ${{ matrix.name }} (HTML)
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_target: ${{ matrix.image }}
          scan_type: "image"  
          scan-scope: "all"
          severity: "HIGH,CRITICAL"  
          format: "table"
          generate_sbom: "false"
          report_suffix: "-image-${{ matrix.name }}-html-CT248"

      - name: Run Trivy Image Scan - ${{ matrix.name }} (SPDX)
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_target: ${{ matrix.image }}
          scan_type: "image"  
          scan-scope: "all"
          severity: "HIGH,CRITICAL"  
          format: "spdx-json"
          scanners: "vuln"
          generate_sbom: "false"
          report_suffix: "-image-${{ matrix.name }}-spdx-CT248"

      - name: Scan Dockerfile - ${{ matrix.name }}
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_type: "config"
          scan_target: ${{ matrix.context }}
          severity: "HIGH,CRITICAL"
          format: "json"
          misconfig_scanners: "dockerfile"
          report_suffix: "-config-${{ matrix.name }}-CT222"
          working_dir: ${{ env.APP_PATH }}

      - name: Upload Trivy Report for ${{ matrix.name }}
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: trivy-report-${{ matrix.name }}
          path: security-results/trivy*

  bandit-scan:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Run Bandit Scan
        uses: open-edge-platform/orch-ci/.github/actions/security/bandit@27276444a9bcf247a27369406686b689933bd1ff
        id: bandit
        with:
          scan-scope: "all"  
          output-format: "txt" 
          fail-on-findings: "false"
          paths: ${{ env.APP_PATH }}
          report_suffix: "-bandit-chat-qna-core-CT161"
          
      - name: Upload Report
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: bandit-report-core
          path: bandit-report-*.txt

  clamav-scan:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Run ClamAV Scan
        uses: open-edge-platform/orch-ci/.github/actions/security/clamav@27276444a9bcf247a27369406686b689933bd1ff
        id: clamav
        with:
          scan-scope: "all"  
          output-format: "txt" 
          fail-on-findings: "false"
          paths: ${{ env.APP_PATH }}
          exclude_dirs: ".git,node_modules,venv,ui/test,tests"
          
      - name: Upload Report
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: clamav-report-${{ env.APP_NAME }}
          path: security-results/clamav*

  gitleaks-scan:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
        with:
          persist-credentials: false
          
      - name: Install gitleaks
        uses: open-edge-platform/orch-ci/.github/actions/bootstrap@5f1c7f544b235db6ded508b6b4c6a2d3a78a38be
        with:
          bootstrap_tools: "gitleaks"
          
      - name: Get current timestamp
        id: timestamp
        run: echo "time=$(date +%s)" >> "$GITHUB_OUTPUT"
        
      - name: Clone CI repo
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
        with:
          repository: open-edge-platform/orch-ci
          path: ci
          persist-credentials: false
          
      - name: Scan for secrets
        run: |
          gitleaks dir ${{ env.APP_PATH }} -v -c ci/.gitleaks.toml --baseline-path ci/gitleaks_baselines/gitleaks-${{ env.APP_NAME }}.json -r gitleaks-${{ env.APP_NAME }}.json || true
          
      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: gitleaks-report-${{ env.APP_NAME }}-${{ steps.timestamp.outputs.time }}
          path: gitleaks-${{ env.APP_NAME }}.json

  shellcheck-scan:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Setup environment with ShellCheck
        uses: open-edge-platform/orch-ci/.github/actions/bootstrap@5f1c7f544b235db6ded508b6b4c6a2d3a78a38be
        with:
          bootstrap_tools: "shellcheck"
      
      - name: Run ShellCheck
        working-directory: ${{ env.APP_PATH }}
        run: make shellcheck
      
      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: shellcheck-report-${{ env.APP_NAME }}
          path: ${{ env.APP_PATH }}/security-results/shellcheck-report-*.txt
  
  pylint-scan:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742-2e395cd74f332709
      
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ needs.setup.outputs.python_version }}
      
      - name: Run Pylint via Makefile
        working-directory: ${{ env.APP_PATH }}
        run: make pylint
      
      - name: Upload Pylint Report
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: pylint-report-${{ env.APP_NAME }}
          path: ${{ env.APP_PATH }}/security-results/pylint-report-*.txt
  
  unit-tests:
    runs-on: ubuntu-22.04-32core-128GB
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Setup Node.js for frontend tests
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}
      
      - name: Set up Python for backend tests
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python_version }}
    
      - name: Run all unit tests via Makefile
        working-directory: ${{ env.APP_PATH }}
        run: make test

      - name: Upload frontend test results
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: frontend-test-results-${{ env.APP_NAME }}
          path: ${{ env.APP_PATH }}/ui/coverage/

      - name: Upload backend test results
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: backend-test-results-${{ env.APP_NAME }}
          path: ${{ env.APP_PATH }}/coverage-backend/